spring:
  devtools:
    restart:
      additional-paths: ./src/main/jte

soli:
  pagination:
    max-size: 100
  administrator:
    password: "{noop}password"
  guest:
    marker: "guest"
  hostname: "http://localhost:8080"
  development-mode: true
  time-zone: "Europe/Berlin"
  holiday-calendar-url: "https://www.thunderbird.net/media/caldata/autogen/GermanHolidays.ics"