spring:
  security:
    oauth2:
      client:
        registration:
          kit:
            client-id: ${KIT_CLIENT_ID}
            client-secret: ${KIT_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "https://cc415dc2-136a-4cfd-adc9-45a126ee849e.ka.bw-cloud-instance.org/login/oauth2/code/{registrationId}"
            client-name: Kit
        provider:
          kit:
            issuer-uri: "https://oidc.scc.kit.edu/auth/realms/kit"
            authorization-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/auth"
            token-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/token"
            user-info-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/userinfo"
  application:
    name: Soli
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "${DB_URL:jdbc:postgres://127.0.0.1:5432/soli}"
    username: "${DB_USERNAME:soli}"
    password: "${DB_PASSWORD:john_soli}"
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
  docker:
    compose:
      skip:
        in-tests: false
  mail:
    host: smtp.kit.edu
    port: 587
    username: ${KIT_MAIL_USERNAME}
    password: ${KIT_MAIL_PASSWORD}
    properties:
      kit:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    path: /error
    whitelabel:
      enabled: false
