soli:
  pagination:
    max-size: 100
  administrator:
    # This should be a hashed environment variable
    # Example: for "password" use {bcrypt}$2a$10$6o.zVr3j/soZPS77kXznXuRBauNdAGPDOm3F7QJimkVQ4LNZ6qws2
    # See https://docs.spring.io/spring-security/reference/servlet/authentication/passwords/in-memory.html for details
    password: "${SOLI_ADMINISTRATOR_PASSWORD}"
  guest:
    marker: "guest"
  hostname: "${SOLI_HOSTNAME}"
  development-mode: false
  time-zone: "${SOLI_TIME_ZONE}"
  holiday-calendar-url: "${SOLI_HOLIDAY_CALENDAR_URL}"