services:
  soli:
    depends_on:
      - database
    image: ghcr.io/solidarische-raumnutzung/solidarische-raumnutzung:latest
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8080:8080"
    volumes:
      - .m2:/root/.m2
    environment:
      SOLI_ADMINISTRATOR_PASSWORD: "{bcrypt}$2a$10$GRLdNijSQMUvl/au9ofL.eDwmoohzzS7.rmNSJZ.0FxO/BTk76klW"
      SOLI_HOSTNAME: "http://localhost:8080"
      KIT_CLIENT_ID: ""
      KIT_CLIENT_SECRET: ""
      KIT_MAIL_USERNAME: ""
      KIT_MAIL_PASSWORD: ""
      DB_URL: jdbc:postgresql://database:5432/soli
      DB_USERNAME: soli
      DB_PASSWORD: john_soli
      SOLI_TIME_ZONE: "Europe/Berlin"
      SOLI_HOLIDAY_CALENDAR_URL: "https://www.thunderbird.net/media/caldata/autogen/GermanHolidays.ics"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "30"
      WATCHTOWER_LABEL_ENABLE: "true"

  database:
    image: postgres:17
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: soli
      POSTGRES_PASSWORD: john_soli
      POSTGRES_DB: soli

  caddy:
    depends_on:
      - soli
    image: caddy:2.9-alpine
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  postgres:
